// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: kvs.proto

package kvspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kvs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	NotLeader     bool                   `protobuf:"varint,3,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,4,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kvs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *GetResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_kvs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotLeader     bool                   `protobuf:"varint,1,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_kvs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *SetResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kvs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotLeader     bool                   `protobuf:"varint,1,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,2,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kvs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *DeleteResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type IncrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrRequest) Reset() {
	*x = IncrRequest{}
	mi := &file_kvs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrRequest) ProtoMessage() {}

func (x *IncrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrRequest.ProtoReflect.Descriptor instead.
func (*IncrRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{6}
}

func (x *IncrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IncrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	NotLeader     bool                   `protobuf:"varint,2,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,3,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrResponse) Reset() {
	*x = IncrResponse{}
	mi := &file_kvs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrResponse) ProtoMessage() {}

func (x *IncrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrResponse.ProtoReflect.Descriptor instead.
func (*IncrResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{7}
}

func (x *IncrResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IncrResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *IncrResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type KeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysRequest) Reset() {
	*x = KeysRequest{}
	mi := &file_kvs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRequest) ProtoMessage() {}

func (x *KeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRequest.ProtoReflect.Descriptor instead.
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{8}
}

func (x *KeysRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type KeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	NotLeader     bool                   `protobuf:"varint,2,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,3,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysResponse) Reset() {
	*x = KeysResponse{}
	mi := &file_kvs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysResponse) ProtoMessage() {}

func (x *KeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysResponse.ProtoReflect.Descriptor instead.
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{9}
}

func (x *KeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeysResponse) GetNotLeader() bool {
	if x != nil {
		return x.NotLeader
	}
	return false
}

func (x *KeysResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_kvs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{10}
}

type StatusResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// "leader" | "follower" | "candidate"
	State         string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Term          uint64 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex   uint64 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex  uint64 `protobuf:"varint,6,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	KeysTotal     int64  `protobuf:"varint,7,opt,name=keys_total,json=keysTotal,proto3" json:"keys_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_kvs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_kvs_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *StatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetKeysTotal() int64 {
	if x != nil {
		return x.KeysTotal
	}
	return 0
}

var File_kvs_proto protoreflect.FileDescriptor

const file_kvs_proto_rawDesc = "" +
	"\n" +
	"\tkvs.proto\x12\x03kvs\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"y\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x03 \x01(\bR\tnotLeader\x12\x1f\n" +
	"\vleader_addr\x18\x04 \x01(\tR\n" +
	"leaderAddr\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"M\n" +
	"\vSetResponse\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x01 \x01(\bR\tnotLeader\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"P\n" +
	"\x0eDeleteResponse\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x01 \x01(\bR\tnotLeader\x12\x1f\n" +
	"\vleader_addr\x18\x02 \x01(\tR\n" +
	"leaderAddr\"\x1f\n" +
	"\vIncrRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"d\n" +
	"\fIncrResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x02 \x01(\bR\tnotLeader\x12\x1f\n" +
	"\vleader_addr\x18\x03 \x01(\tR\n" +
	"leaderAddr\"%\n" +
	"\vKeysRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"b\n" +
	"\fKeysResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x1d\n" +
	"\n" +
	"not_leader\x18\x02 \x01(\bR\tnotLeader\x12\x1f\n" +
	"\vleader_addr\x18\x03 \x01(\tR\n" +
	"leaderAddr\"\x0f\n" +
	"\rStatusRequest\"\xd7\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\tR\bleaderId\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x06 \x01(\x04R\fappliedIndex\x12\x1d\n" +
	"\n" +
	"keys_total\x18\a \x01(\x03R\tkeysTotal2\x99\x02\n" +
	"\x03KVS\x12(\n" +
	"\x03Get\x12\x0f.kvs.GetRequest\x1a\x10.kvs.GetResponse\x12(\n" +
	"\x03Set\x12\x0f.kvs.SetRequest\x1a\x10.kvs.SetResponse\x121\n" +
	"\x06Delete\x12\x12.kvs.DeleteRequest\x1a\x13.kvs.DeleteResponse\x12+\n" +
	"\x04Incr\x12\x10.kvs.IncrRequest\x1a\x11.kvs.IncrResponse\x12+\n" +
	"\x04Keys\x12\x10.kvs.KeysRequest\x1a\x11.kvs.KeysResponse\x121\n" +
	"\x06Status\x12\x12.kvs.StatusRequest\x1a\x13.kvs.StatusResponseB&Z$github.com/noda/linkraft/proto/kvspbb\x06proto3"

var (
	file_kvs_proto_rawDescOnce sync.Once
	file_kvs_proto_rawDescData []byte
)

func file_kvs_proto_rawDescGZIP() []byte {
	file_kvs_proto_rawDescOnce.Do(func() {
		file_kvs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvs_proto_rawDesc), len(file_kvs_proto_rawDesc)))
	})
	return file_kvs_proto_rawDescData
}

var file_kvs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kvs_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: kvs.GetRequest
	(*GetResponse)(nil),    // 1: kvs.GetResponse
	(*SetRequest)(nil),     // 2: kvs.SetRequest
	(*SetResponse)(nil),    // 3: kvs.SetResponse
	(*DeleteRequest)(nil),  // 4: kvs.DeleteRequest
	(*DeleteResponse)(nil), // 5: kvs.DeleteResponse
	(*IncrRequest)(nil),    // 6: kvs.IncrRequest
	(*IncrResponse)(nil),   // 7: kvs.IncrResponse
	(*KeysRequest)(nil),    // 8: kvs.KeysRequest
	(*KeysResponse)(nil),   // 9: kvs.KeysResponse
	(*StatusRequest)(nil),  // 10: kvs.StatusRequest
	(*StatusResponse)(nil), // 11: kvs.StatusResponse
}
var file_kvs_proto_depIdxs = []int32{
	0,  // 0: kvs.KVS.Get:input_type -> kvs.GetRequest
	2,  // 1: kvs.KVS.Set:input_type -> kvs.SetRequest
	4,  // 2: kvs.KVS.Delete:input_type -> kvs.DeleteRequest
	6,  // 3: kvs.KVS.Incr:input_type -> kvs.IncrRequest
	8,  // 4: kvs.KVS.Keys:input_type -> kvs.KeysRequest
	10, // 5: kvs.KVS.Status:input_type -> kvs.StatusRequest
	1,  // 6: kvs.KVS.Get:output_type -> kvs.GetResponse
	3,  // 7: kvs.KVS.Set:output_type -> kvs.SetResponse
	5,  // 8: kvs.KVS.Delete:output_type -> kvs.DeleteResponse
	7,  // 9: kvs.KVS.Incr:output_type -> kvs.IncrResponse
	9,  // 10: kvs.KVS.Keys:output_type -> kvs.KeysResponse
	11, // 11: kvs.KVS.Status:output_type -> kvs.StatusResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_kvs_proto_init() }
func file_kvs_proto_init() {
	if File_kvs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvs_proto_rawDesc), len(file_kvs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvs_proto_goTypes,
		DependencyIndexes: file_kvs_proto_depIdxs,
		MessageInfos:      file_kvs_proto_msgTypes,
	}.Build()
	File_kvs_proto = out.File
	file_kvs_proto_goTypes = nil
	file_kvs_proto_depIdxs = nil
}
